### ISSUE TITLE
Login form: username fields defaults to Mixedcase on android

### ISSUE THREAD

**Issue by alxndrsn** [medic/medic-api#33]
When you click on the username field on android, the default is to make the first character uppercase.  I suspect most users would have a lowercase-only username so it would be nice to either:
1. default to lowercase text in this field, or
2. have case-insensitive username checking

I think this has been filed before, and fixed, but it's still occurring for me on `lg.dev`

**Comment by garethbowen** [comment]
I don't like option 2. What browser and version are you using?

**Comment by alxndrsn** [comment]
`WebView` on the Tecno

**Comment by garethbowen** [comment]
I don't think that version of webview supports autocapitalize  :sadtrombone:

https://www.chromestatus.com/feature/4529989986811904

**Comment by browndav** [comment]
Looks like we just missed it, and `autocapitalize="off"` was added around Chromium 31: https://code.google.com/p/chromium/issues/detail?id=303883

**Comment by garethbowen** [comment]
This was fixed by lowercasing all usernames so now it doesn't matter if it auto capitalises: https://github.com/medic/medic-webapp/issues/2369
