### ISSUE TITLE
Support extracting and update secondary ddocs

### ISSUE THREAD

**Issue by SCdF** [medic/medic-api#36]
We want to be able to have multiple ddocs, but still use one master ddoc. We're going to solve this by having extra ddocs as attachments to the main one, and write some code in medic-api that on boot or ddoc change, evaluate those ddocs to see if they need updating.

**Comment by SCdF** [comment]
https://github.com/medic/medic-api/pull/39

**Comment by garethbowen** [comment]
Nice work. I've added a couple of comments including one bug (I think?). I think it's a bit verbose too - maybe remove the logging for ddocs that aren't new/modified?

**Comment by SCdF** [comment]
Hey @garethbowen I've made some changes based on your suggestions, let's talk about it tonight

**Comment by garethbowen** [comment]
LGTM. @SCdF merge when ready!

**Comment by SCdF** [comment]
Merged
