### ISSUE TITLE
Disallow creating or updating design documents

### ISSUE THREAD

**Issue by SCdF** [medic/medic-api#37]
No user should be able to create or update a design document through medic api. All legitimate use cases for changing ddocs are done through other means.

**Comment by SCdF** [comment]
Or, even better, just make sure we never ship with a couchdb user that people log in as that can change ddocs.

**Comment by SCdF** [comment]
So it looks like we don't need our "admin" users (those who create users) to actually be CouchDB admins. In fact I'm reasonably sure none of our external credentials need to be actual couchdb admin users.

Instead, we should modify the `/_users/_security` document to have our admin users as actual admins of that database, or create a "user-creation" role and apply it to our admin users and use that instead.

This means that CouchDB itself is securing our design documents against badness, instead of us potentially getting it wrong in medic-api.

**Comment by SCdF** [comment]
@browndav is the above a realistic statement? I'd much prefer to close this ticket with that as the resolution, as opposed to writing code.

**Comment by abbyad** [comment]
Our "admin" users may need to be couchdb admins to create users.

**Comment by alxndrsn** [comment]
@marc probably unnecessary - we need API to be creating the users anyway, as they need duplicate documents in different databases (and potentially replications and dbs created aswell).

**Comment by SCdF** [comment]
> Our "admin" users may need to be couchdb admins to create users.

So @abbyad that was the thing I was checking, at least to create users in couch (ignoring any peculiarities of our app) you don't need to be a couchdb "admin" to do that, you just need to be made an admin (or have a role that is an admin) of the `_users` DB.

**Comment by garethbowen** [comment]
We can (and maybe should) implement an API endpoint so the API ends up creating the user with the admin credentials if you have a given medic permission.

**Comment by SCdF** [comment]
@garethbowen let's chat when you're able

**Comment by SCdF** [comment]
Dealt with by https://github.com/medic/medic-webapp/issues/1888
