### ISSUE TITLE
Add logging support: emit URLs and statuses in normal operation; emit full incoming/outgoing request headers/URLs/bodies in debug mode

### ISSUE THREAD

**Issue by browndav** [medic/medic-api#5]
This is a catch-all issue for logging enhancements. We've had some problems with 502s related to medic-api (like https://github.com/medic/medic-webapp/issues/642), and think that additional logging could really help us reproduce and/or track down those proxy interaction issues.

**Comment by garethbowen** [comment]
Ancient.
