### ISSUE TITLE
/api/v1/users should accept list of users

### ISSUE THREAD

**Issue by mandric** [medic/medic-api#65]
There is no way to get a specified list of users, you have to parse all the users and then use the ones you need which is horribly inefficient.  

Also we might consider streaming/throttling/limiting the call because it builds a huge JSON data structure in memory which doesn't scale.  Ideally we would be streaming the JSONs but not sure how to do that from CouchDB.  Might be worth creating a separate issue.

**Comment by garethbowen** [comment]
Ancient. Reopen in medic-webapp when this is needed.
