### ISSUE TITLE
support users export GET /api/v1/export/users

### ISSUE THREAD

**Issue by mandric** [medic/medic-api#66]
There should be an easy way to get user data out of the system in CSV (spreadsheet) format.  This should include `external_id` if it exists on the user-settings doc.  So if there is an external reference to another database it can be linked/joined.

```
GET /api/v1/export/users

username,external_id,person_id,place_id
...
```

**Comment by garethbowen** [comment]
Ancient. Reopen in medic-webapp when this is needed.
