### ISSUE TITLE
DELETE /api/v1/users/{username} should also delete related contacts

### ISSUE THREAD

**Issue by mandric** [medic/medic-api#67]
We delete the user-settings and user doc in this call but orphan the related place (`facility_id`) and person (`contact_id`) docs.  We should have a flag that is passed in or just delete all of them by default.

**Comment by abbyad** [comment]
I'd vote for a **flag** because there are definitely cases where you would not want to delete the associated place and person (eg multiple users associated to the same person or place, or wanting to assign a new/existing user to the place)

**Comment by garethbowen** [comment]
Ancient. Reopen in medic-webapp when this is needed.
