### ISSUE TITLE
support POST /api/v1/import/users 

### ISSUE THREAD

**Issue by mandric** [medic/medic-api#68]
This endpoint would take a list of normalized (it doesn't do any normalization) and check for:

required fields:  name, username, password 
optional fields: phone, external_id, district/parent place

Maybe do some basic validation like check if name, password and username are decent.  Then import that data, generate request bodies and make the calls to POST /api/v1/users.  

Would be nice to have a dryrun option that returns the request bodies that would be used.

See `medic-import/Readme.md` for more information about the import process.

**Comment by garethbowen** [comment]
We haven't had any demand for this yet. Reopen in medic-webapp or medic-configurer if needed.
