### ISSUE TITLE
don't audit docs that match `_local/*`

### ISSUE THREAD

**Issue by mandric** [medic/medic-api#76]
PouchDB using records with IDs like `_local/REswYVXPyo11ScbUaQVi.w==` during the synchronization process.  We probably don't need to audit those records.  Consider adding a strict list of types that we audit, so it must match the `type` property of a document, or way to ignore these records.

**Comment by garethbowen** [comment]
We already have [an exception for _locals](https://github.com/medic/medic-api/blob/develop/server.js#L99-L102). Is it not working?

**Comment by mandric** [comment]
Appears to not be working.

**Comment by garethbowen** [comment]
It works locally. I wonder if nginx is doing something screwy...

**Comment by garethbowen** [comment]
Pouch might be updating them via bulk_docs, not as a direct PUT/POST - that would bypass the explicit exception and end up being audited. That's horrible  :(

**Comment by garethbowen** [comment]
Yeup, that's confirmed - it's sneaking through in a bulk_docs request. I'll fix this later on. Good spotting @mandric
