### ISSUE TITLE
`_bulk_docs` request crashes API (`Cannot set property 'needTransform' of undefined`)

### ISSUE THREAD

**Issue by estellecomment** [medic/medic-api#77]
With api on `develop`, latest (f2a6859), local environment, run : 
`curl http://admin:pass@localhost:5988/medic/_bulk_docs -d '{"docs":[],"new_edits":true}' -H 'Content-Type: application/json'`

and you get an api crash with : 
```
::1 - admin [08/Jun/2016:14:05:43 +0000] "POST /medic/_bulk_docs HTTP/1.1" - - "-" "curl/7.43.0"
UNCAUGHT EXCEPTION!
{ [TypeError: Cannot set property 'needTransform' of undefined]
  domain: 
   Domain {
     domain: null,
     _events: { error: [Function] },
     _eventsCount: 1,
     _maxListeners: undefined,
     members: [] },
  domainThrown: true }
Server error: { [TypeError: Cannot set property 'needTransform' of undefined]
  domain: 
   Domain {
     domain: null,
     _events: { error: [Function] },
     _eventsCount: 1,
     _maxListeners: undefined,
     members: [] },
  domainThrown: true }
undefined
```

The couch logs don't show anything after the session request, the request is not making it to couch : 
`127.0.0.1 - - GET /_session 200`

`master` version for instance returns '[]' and shows the expected 
`127.0.0.1 - - POST /medic/_bulk_docs 201`

**Comment by garethbowen** [comment]
@estellecomment Don't raise issues against medic-api. Raise them in medic-webapp instead.

Fixed in https://github.com/medic/medic-api/commit/547feae7a8e1b31373b011cd36bfb41b30d0543c
