### ISSUE TITLE
add endpoint for exports

### ISSUE THREAD

**Issue by mandric** [medic/medic-api#9]
When third party services like klipfolio are polling for data they would use this URL, it would be a permalink so that the services don't need to modify their definitions and will always get the right format.

e.g. /api/v0.4/export/(args), /api/v0.5/export/(args)

**Comment by garethbowen** [comment]
The API exists at `/api/v1/export/:type/:form?`. I've added documentation to API_v1.md

**Comment by mandric** [comment]
Awesome
